### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jmetrius** [Yannis4444/Matrix-rEFInd#1]
Hey,

thanks for creating this interesting rEFInd theme. Would you mind adding a license to this repository so that the theme can be freely used by others?

See https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository for more information about the process

**Comment by Yannis4444** [comment]
Hi,

thank you for the message. I just added the license.
